/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author EMI VOZ DE ESPERANZA
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIMC = new javax.swing.JButton();
        btnTips = new javax.swing.JButton();
        btnHabitos = new javax.swing.JButton();
        btnDieta = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 420));
        getContentPane().setLayout(null);

        btnIMC.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        btnIMC.setText("IMC");
        btnIMC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIMCActionPerformed(evt);
            }
        });
        getContentPane().add(btnIMC);
        btnIMC.setBounds(460, 130, 50, 20);

        btnTips.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        btnTips.setText("Tips");
        btnTips.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTips);
        btnTips.setBounds(460, 230, 50, 20);

        btnHabitos.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        btnHabitos.setText("Hábitos");
        btnHabitos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHabitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitosActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabitos);
        btnHabitos.setBounds(120, 157, 80, 20);

        btnDieta.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        btnDieta.setText("Dieta");
        btnDieta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDietaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDieta);
        btnDieta.setBounds(120, 260, 80, 20);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CerrarBoton.png"))); // NOI18N
        btnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(620, 320, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Inicio.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 383);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHabitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitosActionPerformed
        Habitos abrir  = new Habitos ();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHabitosActionPerformed

    private void btnIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIMCActionPerformed
        IMC abrir  = new IMC ();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIMCActionPerformed

    private void btnDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDietaActionPerformed
        Dieta abrir  = new Dieta ();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDietaActionPerformed

    private void btnTipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipsActionPerformed
        Tips abrir  = new Tips ();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTipsActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDieta;
    private javax.swing.JButton btnHabitos;
    private javax.swing.JButton btnIMC;
    private javax.swing.JButton btnTips;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
