/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author EMI VOZ DE ESPERANZA
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Resgistrarse
     */
    public Registrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContraseña1 = new javax.swing.JPasswordField();
        txtConfirmContraseña = new javax.swing.JPasswordField();
        btnRegistrate1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 420));
        getContentPane().setLayout(null);

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(290, 100, 140, 20);

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtEmail);
        txtEmail.setBounds(290, 150, 140, 20);

        txtContraseña1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtContraseña1);
        txtContraseña1.setBounds(290, 200, 140, 20);

        txtConfirmContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtConfirmContraseña);
        txtConfirmContraseña.setBounds(290, 250, 140, 20);

        btnRegistrate1.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        btnRegistrate1.setText("Regístrate");
        btnRegistrate1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistrate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrate1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrate1);
        btnRegistrate1.setBounds(290, 280, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Registrarse.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 383);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrate1ActionPerformed

        String Nom, Email;
        int Contra1, Contra2;
        Nom = (txtNombre.getText());
        Email = (txtEmail.getText());
        Contra1 = Integer.parseInt(txtContraseña1.getText());
        Contra2 = Integer.parseInt(txtConfirmContraseña.getText());
        
        if (Contra1 != Contra2) {
            JOptionPane.showMessageDialog(null, "Debes confirmar tu contraseña");
        } else {
            if (Contra1 == Contra2) {
                Inicio abrir  = new Inicio ();
                abrir.setVisible(true);
                this.setVisible(false);
            }
        }  
    }//GEN-LAST:event_btnRegistrate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrate1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPasswordField txtConfirmContraseña;
    public static javax.swing.JPasswordField txtContraseña1;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
